### ISSUE TITLE
mobile navbar toggler's icon is blocked by CSP

### ISSUE THREAD

**Issue by KenanY** [MemeLabs/Rustla2#226]
The navbar toggler that appears in mobile viewports has a "hamburger menu" icon that is unfortunately blocked by the site's CSP. The icon is defined inline:

```css
.navbar-dark .navbar-toggler-icon {
  background-image: url("data:image/svg+xml,%3csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3e%3cpath stroke='rgba(255, 255, 255, 0.5)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e");
}
```

Error from browser devtools:

> Content Security Policy: The page’s settings blocked the loading of a resource at data:image/svg+xml,%3csvg viewBox='0 0 3… (“img-src”).

The fix could be to either adjust the CSP (within reason) to allow this inline image, or replace the image with [the respective Font Awesome icon](https://fontawesome.com/v4.7.0/icon/bars) instead.

## Expected

![image](https://user-images.githubusercontent.com/733364/68722450-7c26e580-0583-11ea-9962-de98cb9c5e89.png)

## Actual

![image](https://user-images.githubusercontent.com/733364/68722326-19cde500-0583-11ea-81e3-f48b5f75387a.png)
